### ISSUE TITLE
Preprocessing of the user_features

### ISSUE THREAD

**Issue by KarlXC** [swdk/LightFm-Recommendation#1]
Hi,

I'm using your code to learn LightFM with user features, so thank you!

One thing I'm not quite sure about, in `config.py` you have:
`(user_age) = _parse_item_metadata2(num_items,user_raw)`

Shouldn't this be called with `num_users` in order to get the correct feature matrix for the users? Now the size adds up to the number of items (1682) and not the number of users (944).

**Comment by swdk** [comment]
Yes, you are right. Thanks for spotting that for me :)
